name: Deploy API to Azure App Service

on:
    push:
      branches: [ main ]
    workflow_dispatch:
      inputs: # allow manual trigger
        environment:
          type: environment
          description: 'Environment to deploy to'
          required: true

env:
  AZURE_APP_SERVICE_NAME: 'app-pvapi-test'
  API_PROJECT: 'ProgressVisualiserApi'
  API_TEST_PROJECT: 'ProgressVisualiserApi.Tests'
  DOTNET_VERSION: '8.0.x'          

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@v4

    - name: Set up .NET ${{ env.DOTNET_VERSION }} environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build API'
      shell: cmd
      run: dotnet build -o output -c Release
      working-directory: ${{ env.API_PROJECT }}
    
    - name: 'Test API'
      shell: cmd
      run: dotnet test
      working-directory: ${{ env.API_TEST_PROJECT }}

    - name: 'Log in to Azure with AZ CLI'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: 'Deploy API to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_APP_SERVICE_NAME }}
        package: '${{ env.API_PROJECT }}/output'