name: Deploy API to Azure Functions

on:
    push:
      branches: [ main ]
    workflow_dispatch:
      inputs: # allow manual trigger
        environment:
          type: environment
          description: 'Environment to deploy to'
          required: true

env:
  AZURE_FUNCTIONAPP_NAME: 'func-pv-test'
  API_PROJECT: 'ProgressVisualizer.Api'
  API_TEST_PROJECT: 'ProgressVisualizer.Api.Tests'
  DOTNET_VERSION: '8.0.x'          

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
        id-token: write # Required for OIDC
    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@v4

    - name: Set up .NET ${{ env.DOTNET_VERSION }} environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build API'
      shell: cmd
      run: dotnet build -o output -c Release
      working-directory: ${{ env.API_PROJECT }}
    
    - name: 'Test API'
      shell: cmd
      run: dotnet test
      working-directory: ${{ env.API_TEST_PROJECT }}

    # OIDC authentication with an Azure Managed Identity
    # They play nicely with Azure Functions, not yet with Azure SQL deployment
    - name: 'Log in to Azure with AZ CLI'
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy API to Azure Functions'
      uses: Azure/functions-action@v1
      id: deploy-to-function-app
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.API_PROJECT }}/output'